from openai import OpenAI
from settings import OPENAI_API_KEY


class DalleService():
    def __init__(self):
        self.client = OpenAI(api_key=OPENAI_API_KEY)

    def generate_dalle_image(self, prompt, size="1024x1792", quality="standard"):
        """
        Download an image generated by OpenAI's DALL-E model based on the given prompt.

        Args:
        - prompt (str): The prompt to generate the image.
        - size (str): The size of the image in the format "widthxheight". Default is "1024x1024".
        - quality (str): The quality of the generated image. Default is "standard".

        Returns:
        - str: The download URL of the image.
        """

        # Generate image URL using OpenAI DALL-E
        response = self.client.images.generate(
            model="dall-e-3",
            prompt=prompt,
            size=size,
            quality=quality,
            n=1,
        )

        # Download the image
        image_url = response.data[0].url
        return image_url
